# Generated by Django 3.1.8 on 2021-06-07 10:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('audio_embed_block', wagtail.core.blocks.StructBlock([('snippet', wagtail.snippets.blocks.SnippetChooserBlock('media_embed.AudioEmbed'))]))], blank=True, null=True),
        ),
    ]
