# Generated by Django 3.1.8 on 2021-06-07 11:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('media_embed_block', wagtail.core.blocks.StructBlock([('snippet', wagtail.snippets.blocks.SnippetChooserBlock('media_embed.MediaEmbed'))]))], blank=True, null=True),
        ),
    ]
