# Generated by Django 3.1.8 on 2021-06-07 14:35

from django.db import migrations
import etna.text_formats.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmedia.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210607_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('media_snippet_block', wagtail.core.blocks.StructBlock([('snippet', wagtail.snippets.blocks.SnippetChooserBlock('media_embed.MediaSnippet', label='Media snippet item'))])), ('media_embed_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(max_length=255)), ('intro', etna.text_formats.blocks.BasicRichTextBlock(required=False)), ('media_embed', wagtailmedia.blocks.AbstractMediaChooserBlock())]))], blank=True, null=True),
        ),
    ]
