# Generated by Django 3.1.8 on 2021-05-28 16:19

from django.db import migrations, models
import django.db.models.deletion
import etna.text_formats.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', etna.text_formats.fields.BasicRichTextField(blank=True)),
                ('audio_media', models.ForeignKey(blank=True, limit_choices_to={'type': 'audio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
            ],
            options={
                'verbose_name_plural': 'Audio embeds',
            },
        ),
    ]
