# Generated by Django 3.1.8 on 2021-06-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('media_embed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioembed',
            name='audio_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
