# Generated by Django 3.1.8 on 2021-06-07 11:12

from django.db import migrations, models
import django.db.models.deletion
import etna.text_formats.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('media_embed', '0002_auto_20210607_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', etna.text_formats.fields.BasicRichTextField(blank=True)),
                ('media_embed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
            ],
            options={
                'verbose_name_plural': 'Media embeds',
            },
        ),
        migrations.DeleteModel(
            name='AudioEmbed',
        ),
    ]
