# Generated by Django 3.1.8 on 2021-06-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('media_embed', '0003_auto_20210607_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaEmbed',
            new_name='MediaSnippet',
        ),
        migrations.AlterModelOptions(
            name='mediasnippet',
            options={'verbose_name_plural': 'Media snippets'},
        ),
    ]
