# Generated by Django 3.1.8 on 2021-05-18 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='FormBuilderPage',
        ),
    ]
