# Generated by Django 3.1.8 on 2021-05-05 15:31

from django.db import migrations
import etna.text_formats.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_componentspage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentspage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', etna.text_formats.blocks.BasicRichTextBlock())], blank=True, null=True),
        ),
    ]
