# Generated by Django 3.1.8 on 2021-05-06 14:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20210505_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentspage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('quote', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100)), ('quote', wagtail.core.blocks.TextBlock(required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100)), ('citation', wagtail.core.blocks.CharBlock(max_length=100))]))], blank=True, null=True),
        ),
    ]
