# Generated by Django 3.1.8 on 2021-05-10 15:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20210507_1545'),
        ('components', '0005_componentspage_body_region_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsPageAlertsPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alerts.alert')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_placements', to='components.componentspage')),
            ],
            options={
                'verbose_name': 'alert placement',
                'verbose_name_plural': 'alert placements',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
