# Generated by Django 3.1.8 on 2021-05-12 16:08

from django.db import migrations
import etna.jumplinks.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_componentspagealertsplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentspage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('quote', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100)), ('quote', wagtail.core.blocks.TextBlock(required=True)), ('attribution', wagtail.core.blocks.CharBlock(max_length=100)), ('citation', wagtail.core.blocks.CharBlock(max_length=100)), ('jumplink', etna.jumplinks.blocks.JumplinkBlock())]))], blank=True, null=True),
        ),
    ]
