# Generated by Django 3.1.8 on 2021-05-06 15:07

from django.db import migrations, models
import etna.text_formats.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', etna.text_formats.fields.BasicRichTextField(max_length=255)),
            ],
        ),
    ]
