# Generated by Django 3.1.8 on 2021-05-07 15:45

from django.db import migrations, models
import etna.text_formats.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20210506_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=etna.text_formats.fields.BasicRichTextField(),
        ),
    ]
