# Generated by Django 3.1.8 on 2021-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20210507_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='cascade',
            field=models.BooleanField(default=False, verbose_name='Display on child pages'),
        ),
    ]
